export const breadcrumbStoryDescriptions: Record<string, string> = {
  'design-system-breadcrumb--feature-guide': 'Breadcrumb가 제공하는 경로 모델, 표현, Dropdown, 접근성 기능을 한눈에 살펴봅니다.',
  'design-system-breadcrumb--basic': 'items 배열에 title과 href를 전달하는 가장 기본적인 Ant Design 호환 사용법입니다.',
  'design-system-breadcrumb--custom-separator': 'separator prop으로 모든 기본 경로 구분자를 교체합니다.',
  'design-system-breadcrumb--icon-and-rich-title': '문자열뿐 아니라 아이콘, strong 등 원하는 ReactNode를 title로 사용합니다.',
  'design-system-breadcrumb--explicit-separator-item': 'type=separator 항목을 경로 사이에 삽입해 위치별로 서로 다른 구분자를 사용합니다.',
  'design-system-breadcrumb--path-and-params': 'path를 앞 경로와 누적하고 params로 동적 세그먼트를 치환해 href를 생성합니다.',
  'design-system-breadcrumb--custom-item-render': 'itemRender가 route, params, routes, paths를 받아 라우터 Link 같은 사용자 요소를 렌더링합니다.',
  'design-system-breadcrumb--dropdown-menu': 'menu가 있는 항목을 hover하면 하위 이동 메뉴가 열립니다.',
  'design-system-breadcrumb--click-triggered-dropdown': 'dropdownProps.trigger를 click으로 지정해 클릭 기반 메뉴를 사용합니다.',
  'design-system-breadcrumb--controlled-dropdown': 'dropdownProps.open과 onOpenChange로 메뉴 열림 상태를 부모에서 제어합니다.',
  'design-system-breadcrumb--custom-dropdown-icon': 'dropdownIcon으로 모든 메뉴형 Breadcrumb의 펼침 표시를 교체합니다.',
  'design-system-breadcrumb--portal-and-top-placement': 'getPopupContainer로 메뉴를 body에 포털 렌더링하고 topLeft에 배치합니다.',
  'design-system-breadcrumb--disabled-dropdown': 'dropdownProps.disabled로 메뉴형 경로를 비활성화하고 포커스·열기 동작을 막습니다.',
  'design-system-breadcrumb--semantic-class-names-and-styles': 'v6 방식의 semantic classNames와 styles 객체·함수로 root, item, separator를 꾸밉니다.',
  'design-system-breadcrumb--native-navigation-props': 'aria, data, className, style 같은 네이티브 nav 속성을 루트에 직접 전달합니다.',
  'design-system-breadcrumb--legacy-routes': '기존 코드 이전을 위해 deprecated routes 별칭도 items와 동일하게 처리합니다.',
  'design-system-breadcrumb--legacy-children-composition': 'deprecated Breadcrumb.Item과 Breadcrumb.Separator JSX 조합 API를 호환합니다.',
  'design-system-breadcrumb--legacy-children-menu': '기존 route children 데이터를 Dropdown menu 항목으로 자동 변환합니다.',
  'design-system-breadcrumb--responsive-long-trail': '긴 경로가 좁은 화면에서 잘리지 않고 여러 줄로 자연스럽게 감깁니다.',
  'design-system-breadcrumb--menu-callbacks': '메뉴 항목, menu.onClick, dropdown onOpenChange 콜백 계약을 확인합니다.',
  'design-system-breadcrumb--item-click-and-attributes': 'RouteItem의 onClick, className, style, aria와 data 속성이 실제 링크에 전달되는지 확인합니다.',
  'design-system-breadcrumb--generic-params-typing': '제네릭 params 타입으로 동적 경로 키와 값을 TypeScript에서 명확히 관리합니다.',
  'design-system-breadcrumb--empty': 'items가 비어 있어도 접근 가능한 빈 nav 구조를 안정적으로 렌더링합니다.',
}
